import type { Metadata } from 'next'
import { businessInfo } from './businessInfo'

type OgImage = { url: string; width: number; height: number; alt: string }

/**
 * Sitewide default `og:image` / `twitter:image` (issue #20 / tech-audit H-3).
 * Generated by `scripts/generate-og-image.mjs` — see that file for how and
 * why (real project photo + brand mark + headline, committed as a single
 * static JPEG rather than rendered per-request).
 */
const DEFAULT_OG_IMAGE: OgImage = {
  url: '/og/default.jpg',
  width: 1200,
  height: 630,
  alt: 'Elite Touch Renovations — bathroom renovations across Sydney',
}

type BuildMetadataInput = {
  /** Site-relative path, leading + trailing slash — e.g. '/packages/' or '/'. */
  path: string
  title: string
  description: string
  /** `og:type`. Defaults to 'website'; gallery project pages pass 'article'. */
  type?: 'website' | 'article'
  /**
   * `og:image` / `twitter:image` override, with real dimensions and an `alt`
   * — required fields, not optional, because a raw string URL with no
   * width/height is exactly the gallery-page gap H-3 flagged (no
   * `og:image:width`/`height`, `twitter:card` stuck on `summary`). Omit to
   * use `DEFAULT_OG_IMAGE`, which every page now gets.
   */
  images?: OgImage[]
}

/**
 * One shared page-metadata builder (issue #19 / tech-audit H-2).
 *
 * `app/layout.tsx` sets a sitewide `openGraph` default, including
 * `openGraph.url: businessInfo.siteUrl` — the homepage. Next.js metadata is
 * merged SHALLOWLY between layout and page (duplicate keys are REPLACED, not
 * deep-merged — see "Merging" in Next's `generate-metadata` docs), so any page
 * that does not set its own `openGraph` silently ships the homepage's
 * `og:url`, and any page that DOES set its own `openGraph` (the gallery
 * project pages, for `og:type: 'article'`) REPLACES the whole object —
 * `openGraph.locale` and `openGraph.siteName` vanish from that page's
 * `<meta>` tags entirely. Both were verified missing/wrong in the served HTML
 * before this fix (packages: `og:url` = homepage; gallery detail: no
 * `og:site_name`, no `og:locale`, no `og:url` at all).
 *
 * `openGraph.title` / `openGraph.description` are deliberately left unset.
 * Next auto-fills them from the page's own `title` / `description` — already
 * resolved through the root layout's title template — when `openGraph` sets
 * neither (`postProcessMetadata` in `next/dist/lib/metadata/resolve-metadata.js`).
 * That auto-fill then feeds `twitter:title` / `twitter:description` too.
 * Setting them explicitly here would freeze `og:title` at the RAW page title,
 * losing the " | Elite Touch Renovations" suffix every other page's
 * `og:title` carries — exactly the gap the gallery pages had before this
 * helper existed (confirmed in their served HTML: `og:title` had no suffix).
 *
 * `twitter.card` is NOT set here — the root layout sets it once
 * (`summary_large_image`) and every page below it keeps that value, because
 * Next's shallow merge only replaces keys a page's own metadata actually
 * sets, and no page here sets `twitter`. `twitter:image` still auto-fills
 * per-page from this function's own `openGraph.images` (same mechanism as
 * the title/description auto-fill above).
 */
export function buildMetadata({
  path,
  title,
  description,
  type = 'website',
  images = [DEFAULT_OG_IMAGE],
}: BuildMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      locale: 'en_AU',
      siteName: businessInfo.name,
      url: path,
      images,
    },
  }
}
